export const deals = [
    {
        image:"images/deals/deal01.jpg"
    },
    {
        image:"images/deals/deal02.jpg"
    },
    {
        image:"images/deals/deal03.jpg"
    },
    {
        image:"images/deals/deal04.jpg"
    },
    {
        image:"images/deals/deal05.jpg"
    },
    {
        image:"images/deals/deal06.jpg"
    },
    {
        image:"images/deals/deal07.jpg"
    },
    {
        image:"images/deals/deal08.jpg"
    },
    {
        image:"images/deals/deal09.jpg"
    },
    {
        image:"images/deals/deal10.jpg"
    },
    {
        image:"images/deals/deal11.jpg"
    },
    {
        image:"images/deals/deal12.jpg"
    },
]