export const deals = [
    {
        image:"images/deals/deal01.jpg",
        slug:"deal01",
    },
    {
        image:"images/deals/deal02.jpg",
        slug:"deal02",
    },
    {
        image:"images/deals/deal03.jpg",
        slug:"deal03",
    },
    {
        image:"images/deals/deal04.jpg",
        slug:"deal04",
    },
    {
        image:"images/deals/deal05.jpg",
        slug:"deal05",
    },
    {
        image:"images/deals/deal06.jpg",
        slug:"deal06",
    },
    {
        image:"images/deals/deal07.jpg",
        slug:"deal07",
    },
    {
        image:"images/deals/deal08.jpg",
        slug:"deal08",
    },
    {
        image:"images/deals/deal09.jpg",
        slug:"deal09",
    },
    {
        image:"images/deals/deal10.jpg",
        slug:"deal010",
    },
    {
        image:"images/deals/deal11.jpg",
        slug:"deal11",
    },
    {
        image:"images/deals/deal12.jpg",
        slug:"deal12",
    },
]